version: '3'
services:
  web:
    build:
      context: './src/ui'
      dockerfile: 'Dockerfile'
    container_name: web
    volumes:
      - ./src/ui:/app/
    ports: 
      - 3000:3000 
  server:
    build:
      context: './src/server'
      dockerfile: 'Dockerfile'
    container_name: server
    volumes:
      - ./src/server:/usr/src/app/
    depends_on:
      - mysql
    restart: on-failure
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=http_gateway_grpc
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - bridge
  gateway:
    build:
      context: './src/gateway'
      dockerfile: 'Dockerfile.debug'
    container_name: gateway
    ports: 
      - 8080:8080
      - 4000:4000
    depends_on:
      - server
    restart: on-failure
    volumes:
      - ./src/gateway:/usr/src/app/
    networks:
      - bridge
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 9080:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - bridge
    depends_on:
      - gateway
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./config/data/schemas.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./config/data/data.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
      - bridge
networks:
  bridge:
    driver: bridge