version: '3'
services:
  server:
    build:
      context: './src/server'
      dockerfile: 'Dockerfile'
    container_name: server
    volumes:
      - ./src/server:/usr/src/app/
    depends_on:
      - mysql
    restart: on-failure
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=http_gateway_grpc
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - bridge
  gateway:
    build:
      context: './src/gateway'
      dockerfile: 'Dockerfile'
    container_name: gateway
    ports: 
      - 9091:8080 
    depends_on:
      - server
    restart: on-failure
    volumes:
      - ./src/gateway:/usr/src/app/
    networks:
      - bridge
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./config/data/schemas.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./config/data/data.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
      - bridge
networks:
  bridge:
    driver: bridge