// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OrderHandler_GetOrders_FullMethodName = "/order.OrderHandler/GetOrders"
)

// OrderHandlerClient is the client API for OrderHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderHandlerClient interface {
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
}

type orderHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderHandlerClient(cc grpc.ClientConnInterface) OrderHandlerClient {
	return &orderHandlerClient{cc}
}

func (c *orderHandlerClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, OrderHandler_GetOrders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderHandlerServer is the server API for OrderHandler service.
// All implementations should embed UnimplementedOrderHandlerServer
// for forward compatibility
type OrderHandlerServer interface {
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error)
}

// UnimplementedOrderHandlerServer should be embedded to have forward compatible implementations.
type UnimplementedOrderHandlerServer struct {
}

func (UnimplementedOrderHandlerServer) GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrders not implemented")
}

// UnsafeOrderHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderHandlerServer will
// result in compilation errors.
type UnsafeOrderHandlerServer interface {
	mustEmbedUnimplementedOrderHandlerServer()
}

func RegisterOrderHandlerServer(s grpc.ServiceRegistrar, srv OrderHandlerServer) {
	s.RegisterService(&OrderHandler_ServiceDesc, srv)
}

func _OrderHandler_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderHandlerServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderHandler_GetOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderHandlerServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderHandler_ServiceDesc is the grpc.ServiceDesc for OrderHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderHandler",
	HandlerType: (*OrderHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrders",
			Handler:    _OrderHandler_GetOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
